### ISSUE TITLE
Growth graph for citizen usage of web portal

### ISSUE THREAD

**Issue by antonmc** [antonmc/ima#15]

**Comment by dpf2000** [comment]
Access this link to see the numbers I've gathered until yesterday (august 10,2017): https://docs.google.com/spreadsheets/d/1dqeg01ipMbgcB2vC-enT0z_6YWhXeKmTPC5TmsVhS40/edit?usp=sharing

**Comment by dpf2000** [comment]
I made some improvements on the graph to include totalized information about user grow. Please, take a look and tell me if is ok for all of you. The link is the same above.

**Comment by antonmc** [comment]
This looks great ... thanks :)
