### ISSUE TITLE
Mobile app growth chart so far

### ISSUE THREAD

**Issue by antonmc** [antonmc/ima#17]

**Comment by dpf2000** [comment]
Inside IMA network you can access this link to have some data about this matter: https://gateway-cidadao.campinas.sp.gov.br/estatisticas

**Comment by dpf2000** [comment]
We've this numbers right now (august 11, 2017)

![image](https://user-images.githubusercontent.com/30841246/29216920-8dfbd7a6-7e86-11e7-92b0-68f71d157c79.png)

**Comment by dpf2000** [comment]
Is this the kind of data you want?
